blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static






from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
)

from . import views

urlpatterns = [
    path('', views.PostListView, name='blog-home'),
    path('user/<str:username>', views.UserPostListView, name='user-posts'),
    path('post/<int:id>/', views.PostDetailView, name='post-detail'),
    path('post/new/', views.PostCreateView, name='post-create'),
    path('post/<int:id>/update/', views.PostUpdateView, name='post-update'),
    path('post/<int:id>/delete/', views.PostDeleteView, name='post-delete'),
    path('about/', views.about, name='blog-about'),
    #path('pay_success/', views.pay_success, name='blog-pay_success'),
    path('footer/', views.footer, name='blog-footer'),
    path('navigation/', views.navigation, name='blog-navigation'),
    path('success/', views.Success, name='blog-success'),
    path('contact/', views.Contact, name='blog-contact'),
    path('base/', views.base, name='blog-base'),
]

houses/urls.py
from django.conf.urls import url
from .views import (house_index)
from . import views

app_name='houses'

urlpatterns = [
    url(r'^$', views.house_index, name="house_index"),
    url(r'^(?P<id>[\w-]+)/$', views.house_detail, name="house_detail"),
]

sawasawa_market/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls import url, include
from django.conf import settings
from blog import views
from django.conf.urls.static import static
from users import views as user_views
from search import urls as urls_search
from checkout import views as checkout_views




urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^search/', include(urls_search)),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('', include('checkout.urls')),
    path('', include('blog.urls')),
    path('blogo/', include('blogo.urls')),
    url(r'^jobbs/', include('jobbs.urls')),
    url(r'^houses/', include('houses.urls')),
    url(r'^cars/', include('cars.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    
    

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)

houses/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.


class House(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    room = models.CharField(max_length=20)
    area = models.CharField(max_length=20)
    price = models.IntegerField()
    image = models.ImageField(
        default='default.jpg', upload_to='image_jobbs', blank=True, null=True)
    phone = models.CharField(blank=True, max_length=15)
    address = models.CharField(help_text='Address', max_length=60)
    city = models.CharField(help_text='City', max_length=40)
    country = models.CharField(help_text='Country', max_length=30)
    date_posted = models.DateTimeField(default=timezone.now)
    

houses/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse 
from .models import House


# Create your views here.
def house_index(request):
    houses = House.objects.all()
    context = {'houses': houses}

    template_name = 'house_index.html'  
    context_object_name = 'houses'
    return render(request, 'house_index.html', context)


def house_detail(request, id):
    
    house = get_object_or_404(House, id=id)
    context = {'house': house}
    template_name = 'house_detail.html'
    return HttpResponse(render(request, 'house_detail.html', context))

houses/templates/house_detail.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
{% include 'blog/navigation.html' %}

<a  href="{% url 'houses:house_index' %}" class="btn margin-bottom-cat margin-right-cat" ><i class="fas fa-arrow-left"></i><i class="fas fa-store-alt fa indigo-text"></i>🏠 house for sell/rent </a>
<div class="container my-5">


  <!--Section: Content-->
  <section class="magazine-section dark-grey-text">

    <!-- Section heading -->
    <h3 class="text-center font-weight-bold mb-4 pb-2">House Detail</h3>
    <!-- Section description -->
  	<!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-lg-4 col-md-12 mb-4">

        <!-- Featured news -->
        <div class="single-news">

          <!-- Image -->
          <div class="view overlay rounded z-depth-1-half mb-4">
            <img class="img-fluid" src="{{ house.image.url }}" alt="" >
            <a>
              <div class="mask rgba-white-slight"></div>
            </a>
          </div>

          <!-- Data -->
          <div class="news-data d-flex justify-content-between">
            <a href="#!" class="deep-orange-text">
              <h6 class="font-weight-bold"><i class="fas fa-city"></i></h6>
            </a>
            <p class="font-weight-bold dark-grey-text"><i class="fas fa-clock-o pr-2"></i>{{ house.date_posted }}</p>
          </div>

          <!-- Excerpt -->
          <h3 class="text-center mt-3 font-weight-bold dark-grey-text mb-3"><a>{{ house.title }}</a></h3>
          <p class="dark-grey-text">{{ house.description }}</p>
        </div>
        <!-- Featured news -->

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-lg-6 col-md-12 mb-4">

<!-- Small news -->
        <div class="single-news mb-4">

          <!-- Grid row -->
          <div class="row">

            <!-- Grid column -->
            <div class="ml-4">

              <!--Image-->
              <div class="view  mb-4">
                <i class="fas fa-hand-holding-usd orange-text accent-1"></i>
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-9">

              <!-- Excerpt -->
              <p class="font-weight-bold dark-grey-text">PRICE</p>
              <div class="d-flex justify-content-between">
                <div class="col-11 text-truncate pl-0 mb-3">
                  <a href="#!" class="dark-grey-text">{{ house.price }} $</a>
                </div>
              </div>

            </div>
            <!-- Grid column -->

          </div>
          <!-- Grid row -->

        </div>
        <!-- Small news -->

        <!-- Small news -->
        <div class="single-news mb-4">

          <!-- Grid row -->
          <div class="row">

            <!-- Grid column -->
            <div class="ml-4">

              <!--Image-->
              <div class="view  mb-4">
                <i class="fas fa-chart-area orange-text accent-1"></i>
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-9">

              <!-- Excerpt -->
              <p class="font-weight-bold dark-grey-text">AREA</p>
              <div class="d-flex justify-content-between">
                <div class="col-11 text-truncate pl-0 mb-3">
                  <a href="#!" class="dark-grey-text">{{ house.area }}</a>
                </div>
              </div>

            </div>
            <!-- Grid column -->

          </div>
          <!-- Grid row -->

        </div>
        <!-- Small news -->
        
<!-- Small news -->
        <div class="single-news mb-4">

          <!-- Grid row -->
          <div class="row">

            <!-- Grid column -->
            <div class="ml-4">

              <!--Image-->
              <div class="view  mb-4">
               <i class="fas fa-door-open orange-text accent-1"></i>
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-9">

              <!-- Excerpt -->
              <p class="font-weight-bold dark-grey-text">ROOMS</p>
              <div class="d-flex justify-content-between">
                <div class="col-11 text-truncate pl-0 mb-3">
                  <a href="#!" class="dark-grey-text">{{ house.room }}</a>
                </div>
                
              </div>

            </div>
            <!-- Grid column -->

          </div>
          <!-- Grid row -->

        </div>
        <!-- Small news -->
        <!-- Small news -->
        <div class="single-news mb-4">

          <!-- Grid row -->
          <div class="row">

            <!-- Grid column -->
            <div class="ml-4">

              <!--Image-->
              <div class="view  mb-4">
                <i class="fas fa-phone-volume orange-text accent-1"></i>
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-9">

              <!-- Excerpt -->
              <p class="font-weight-bold dark-grey-text">PHONE</p>
              <div class="d-flex justify-content-between">
                <div class="col-11 text-truncate pl-0 mb-3">
                  <a href="#!" class="dark-grey-text">{{ house.phone }}</a>
                </div>
                
              </div>

            </div>
            <!-- Grid column -->

          </div>
          <!-- Grid row -->

        </div>
        <!-- Small news -->

        <!-- Small news -->
        <div class="single-news mb-4">

          <!-- Grid row -->
          <div class="row">

            <!-- Grid column -->
            <div class="ml-4">

              <!--Image-->
              <div class=" view  mb-4">
                <i class="far fa-envelope orange-text accent-1"></i>
              </div>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-9">

              <!-- Excerpt -->
              <p class="font-weight-bold dark-grey-text">Email</p>
              <div class="d-flex justify-content-between">
                <div class="col-11 text-truncate pl-0 mb-3">
                  <a href="#!" class="dark-grey-text">email....</a>
                </div>
               
              </div>

            </div>
            <!-- Grid column -->

          </div>
          <!-- Grid row -->

        </div>
        <!-- Small news -->

        <!-- Small news -->
        <div class="single-news mb-4">

          <!-- Grid row -->
          <div class="row">

            <!-- Grid column -->
            <div class="ml-4">

              <!--Image-->
              <div class="view mb-4">
                <i class="fas fa-map-marker orange-text accent-1"></i>
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-9">

              <!-- Excerpt -->
              <p class="font-weight-bold dark-grey-text">ADDRESS</p>
              <div class="d-flex justify-content-between">
                <div class="col-11 text-truncate pl-0 mb-3">
                  <a href="#!" class="dark-grey-text">{{ house.address }}</a>
                </div>
              </div>

            </div>
            <!-- Grid column -->

          </div>
          <!-- Grid row -->

        </div>
        <!-- Small news -->

        <!-- Small news -->
        <div class="single-news">

          <!-- Grid row -->
          <div class="row">

            <!-- Grid column -->
            <div class="ml-4">

              <!--Image-->
              <div class="view mb-4">
                <i class="fas fa-city orange-text accent-1"></i>
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-9">

              <!-- Excerpt -->
              <p class="font-weight-bold dark-grey-text">CITY</p>
              <div class="d-flex justify-content-between">
                <div class="col-11 text-truncate pl-0 mb-lg-3">
                  <a href="#!" class="dark-grey-text">{{ house.city }}</a>
                </div>
               
              </div>

            </div>
            <!-- Grid column -->

          </div>
          <!-- Grid row -->

        </div>
        <!-- Small news -->



<!-- Small news -->
        <div class="single-news">

          <!-- Grid row -->
          <div class="row">

            <!-- Grid column -->
            <div class="ml-4">

              <!--Image-->
              <div class="view  mb-md-0 mb-4">
                <i class="fas fa-globe-africa orange-text accent-1"></i>
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-9">

              <!-- Excerpt -->
              <p class="font-weight-bold dark-grey-text">COUNTRY</p>
              <div class="d-flex justify-content-between">
                <div class="col-11 text-truncate pl-0 mb-lg-3">
                  <a href="#!" class="dark-grey-text">{{ house.country }}</a>
                </div>
               
              </div>

            </div>
            <!-- Grid column -->

            

          </div>
          <!-- Grid row -->

        </div>
        <!-- Small news -->

      </div>
      <!--Grid column-->

    </div>
    <!-- Grid row -->

  </section>
  <!--Section: Content-->
</div>

{% include 'blog/footer.html' %}
{% endblock %}

houses/templates/house_index.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
{% include 'blog/navigation.html' %}
<h3 class=" margin-bottom-cat margin-right-cat text-center deep-orange-text mt-2" >🏠 House for Sale/Rent </h3>
<div class="container">
<div class="row">
{% for house in houses %}
    <div class="col-md-4">
        <div class="card mb-2 rounded z-depth-2">
            <img class="card-img-top img-thumbnail img-fluid imgs-details" src="{{ house.image.url }}">
            <div class="card-body">
                <h5 class="card-title">{{ house.title }}</h5>
                <p class="card-text">{{ house.description|linebreaks|truncatewords:10 }}</p>
                <a href="{% url 'houses:house_detail' id=house.id %}"
                   class="btn btn-pink btn-rounded btn-md">
                    Read More
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
</div>

<div class="django_form_clear">
{% include 'blog/footer.html' %}
</div>
{% endblock %}
 