blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static






from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
)

from . import views

urlpatterns = [
    path('', views.PostListView, name='blog-home'),
    path('user/<str:username>', views.UserPostListView, name='user-posts'),
    path('post/<int:id>/', views.PostDetailView, name='post-detail'),
    path('post/new/', views.PostCreateView, name='post-create'),
    path('post/<int:id>/update/', views.PostUpdateView, name='post-update'),
    path('post/<int:id>/delete/', views.PostDeleteView, name='post-delete'),
    path('about/', views.about, name='blog-about'),
    #path('pay_success/', views.pay_success, name='blog-pay_success'),
    path('footer/', views.footer, name='blog-footer'),
    path('navigation/', views.navigation, name='blog-navigation'),
    path('success/', views.Success, name='blog-success'),
    path('contact/', views.Contact, name='blog-contact'),
    path('base/', views.base, name='blog-base'),
]

jobbs/urls.py
from django.conf.urls import url
from .views import (job_index)
from . import views

app_name='jobbs'

urlpatterns = [
    url(r'^$', views.job_index, name="job_index"),
    url(r'^(?P<id>[\w-]+)/$', views.job_detail, name="job_detail"),
]

sawasawa_market/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls import url, include
from django.conf import settings
from blog import views
from django.conf.urls.static import static
from users import views as user_views
from search import urls as urls_search
from checkout import views as checkout_views




urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^search/', include(urls_search)),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('', include('checkout.urls')),
    path('', include('blog.urls')),
    path('blogo/', include('blogo.urls')),
    url(r'^jobbs/', include('jobbs.urls')),
    url(r'^houses/', include('houses.urls')),
    url(r'^cars/', include('cars.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    
    

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)

jobbs/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.urls import reverse


class Job(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.ImageField(
        default='default.jpg', upload_to='image_jobbs', blank=True, null=True)
    phone = models.CharField(blank=True, max_length=15)
    address = models.CharField(help_text='Address', max_length=60)
    city = models.CharField(help_text='City', max_length=40)
    country = models.CharField(help_text='Country', max_length=30)
    date_posted = models.DateTimeField(default=timezone.now)


class Meta:
    ordering = ['-id']


def __str__(self):
        return self.title

    

jobbs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse 
from .models import Job


# Create your views here.
def job_index(request):
    jobbs = Job.objects.all()
    context = {'jobbs': jobbs}
    template_name = 'job_index.html'  
    context_object_name = 'jobbs'
    return render(request, 'job_index.html', context)


def job_detail(request, id):
    
    jobb = get_object_or_404(Job, id=id)
    context = {'jobb': jobb}
    template_name = 'job_detail.html'
    return HttpResponse(render(request, 'job_detail.html', context))


 

jobbs/templates/job_detail.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
{% include 'blog/navigation.html' %}
<a href="{% url 'jobbs:job_index' %}" class="btn margin-bottom-cat margin-right-cat" aria-hidden="true"><i class="fas fa-arrow-left"></i><i class="fas fa-user-graduate fa purple-text"></i><i class="fas fa-user-md fa deep-purple-text"></i><strong> training & jobs</a>
<div class="container my-5">
<!--Section: Content-->
  <section class="magazine-section dark-grey-text">
<!--job post details-->
    <!-- Section heading -->
    <h3 class="text-center font-weight-bold mb-4 pb-2">Detail</h3>
    <!-- Section description -->
    <p class="text-center font-weight-bold orange-text w-responsive mx-auto mb-5">Technologies: {{ jobb.technology }}</p>

  	<!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-lg-6 col-md-12 mb-4">

        <!-- Featured news -->
        <div class="single-news">

          <!-- Image -->
          <div class="view overlay rounded z-depth-1-half mb-4">
            <img class="img-fluid" src="{{ jobb.image.url }}" alt="">
            <a>
              <div class="mask rgba-white-slight"></div>
            </a>
          </div>

          <!-- Data -->
          <div class="news-data d-flex justify-content-between">
            <a href="#!" class="deep-orange-text">
            </a>
            <p class="font-weight-bold dark-grey-text"><i class="fas fa-clock-o pr-2 orange-text accent-1"></i>{{ jobb.date_posted }}</p>
          </div>

          <!-- Excerpt -->
          <h3 class="text-center font-weight-bold dark-grey-text mb-3"><a>{{ jobb.title }}</a></h3>
          <p class="dark-grey-text">{{ jobb.description }}</p>
        </div>
        <!-- Featured news -->

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-lg-6 col-md-12 mb-4">

        <!-- Small news -->
        <div class="single-news mb-4">

          <!-- Grid row -->
          <div class="row">

            <!-- Grid column -->
            <div class="ml-4">

              <!--Image-->
              <div class="view  mb-4">
                <i class="fas fa-phone-volume orange-text accent-1"></i>
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-9">

              <!-- Excerpt -->
              <p class="font-weight-bold dark-grey-text">PHONE</p>
              <div class="d-flex justify-content-between">
                <div class="col-11 text-truncate pl-0 mb-3">
                  <a href="#!" class="dark-grey-text">{{ jobb.phone }}</a>
                </div>
                <a><i class="fas fa-angle-double-right green-text accent-1"></i></a>
              </div>

            </div>
            <!-- Grid column -->

          </div>
          <!-- Grid row -->

        </div>
        <!-- Small news -->

        <!-- Small news -->
        <div class="single-news mb-4">

          <!-- Grid row -->
          <div class="row">

            <!-- Grid column -->
            <div class="ml-4">

              <!--Image-->
              <div class=" view  mb-4">
                <i class="far fa-envelope orange-text accent-1"></i>
              </div>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-9">

              <!-- Excerpt -->
              <p class="font-weight-bold dark-grey-text">Email</p>
              <div class="d-flex justify-content-between">
                <div class="col-11 text-truncate pl-0 mb-3">
                  <a href="#!" class="dark-grey-text">email....</a>
                </div>
                <a><i class="fas fa-angle-double-right green-text accent-1"></i></a>
              </div>

            </div>
            <!-- Grid column -->

          </div>
          <!-- Grid row -->

        </div>
        <!-- Small news -->

        <!-- Small news -->
        <div class="single-news mb-4">

          <!-- Grid row -->
          <div class="row">

            <!-- Grid column -->
            <div class="ml-4">

              <!--Image-->
              <div class="view  mb-4">
                <i class="fas fa-map-marker orange-text accent-1"></i>
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-9">

              <!-- Excerpt -->
              <p class="font-weight-bold dark-grey-text">ADDRESS</p>
              <div class="d-flex justify-content-between">
                <div class="col-11 text-truncate pl-0 mb-3">
                  <a href="#!" class="dark-grey-text">{{ jobb.address }}</a>
                </div>
                <a><i class="fas fa-angle-double-right green-text accent-1"></i></a>
              </div>

            </div>
            <!-- Grid column -->

          </div>
          <!-- Grid row -->

        </div>
        <!-- Small news -->

        <!-- Small news -->
        <div class="single-news">

          <!-- Grid row -->
          <div class="row">

            <!-- Grid column -->
            <div class="ml-4">

              <!--Image-->
              <div class="view  mb-md-0 mb-4">
                <i class="fas fa-city orange-text accent-1"></i>
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-9">

              <!-- Excerpt -->
              <p class="font-weight-bold dark-grey-text">CITY</p>
              <div class="d-flex justify-content-between">
                <div class="col-11 text-truncate pl-0 mb-lg-3">
                  <a href="#!" class="dark-grey-text">{{ jobb.city }}</a>
                </div>
                <a><i class="fas fa-angle-double-right green-text accent-1"></i></a>
              </div>

            </div>
            <!-- Grid column -->

          </div>
          <!-- Grid row -->

        </div>
        <!-- Small news -->
<!-- Small news -->
        <div class="single-news">

          <!-- Grid row -->
          <div class="row">

            <!-- Grid column -->
            <div class="ml-4">

              <!--Image-->
              <div class="view  mb-md-0 mb-4">
                <i class="fas fa-globe-africa orange-text accent-1"></i>
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-9">

              <!-- Excerpt -->
              <p class="font-weight-bold dark-grey-text">COUNTRY</p>
              <div class="d-flex justify-content-between">
                <div class="col-11 text-truncate pl-0 mb-lg-3">
                  <a href="#!" class="dark-grey-text">{{ jobb.country }}</a>
                </div>
                <a><i class="fas fa-angle-double-right green-text accent-1"></i></a>
              </div>

            </div>
            <!-- Grid column -->

            

          </div>
          <!-- Grid row -->

        </div>
        <!-- Small news -->

      </div>
      <!--Grid column-->

    </div>
    <!-- Grid row -->

  </section>
  <!--Section: Content-->
</div>
{% include 'blog/footer.html' %}
{% endblock %}

jobbs/templates/job_index.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
{% include 'blog/navigation.html' %}
<h2  class=" margin-bottom-cat margin-right-cat text-center  orange-text" aria-hidden="true"><i class="fas fa-user-graduate fa-x purple-text mr-2 mt-2"></i><i class="fas fa-user-md fa-x deep-purple-text mr-2 mt-2"></i><strong> Training & Jobs</h2>
<div class="container">
<div class="row">
<!--job post -->
{% for jobb in jobbs %}
    <div class="col-md-4">
        <div class="card mb-2 rounded z-depth-2">
            <img class="card-img-top img-thumbnail img-fluid imgs-details" src="{{ jobb.image.url }}">
            <div class="card-body">
                <h5 class="card-title">{{ jobb.title }}</h5>
                <p class="card-text">{{ jobb.description|linebreaks|truncatewords:10 }}</p>
                <a href="{% url 'jobbs:job_detail' id=jobb.id %}"
                   class="btn btn-success btn-md btn-rounded mx-0">
                    Read More
                       
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
</div>
{% include 'blog/footer.html' %}
{% endblock %}
 