blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static






from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
)

from . import views

urlpatterns = [
    path('', views.PostListView, name='blog-home'),
    path('user/<str:username>', views.UserPostListView, name='user-posts'),
    path('post/<int:id>/', views.PostDetailView, name='post-detail'),
    path('post/new/', views.PostCreateView, name='post-create'),
    path('post/<int:id>/update/', views.PostUpdateView, name='post-update'),
    path('post/<int:id>/delete/', views.PostDeleteView, name='post-delete'),
    path('about/', views.about, name='blog-about'),
    #path('pay_success/', views.pay_success, name='blog-pay_success'),
    path('footer/', views.footer, name='blog-footer'),
    path('navigation/', views.navigation, name='blog-navigation'),
    path('success/', views.Success, name='blog-success'),
    path('contact/', views.Contact, name='blog-contact'),
    path('base/', views.base, name='blog-base'),
]

cars/urls.py
from django.conf.urls import url
from .views import (car_index)
from . import views

app_name='cars'

urlpatterns = [
    url(r'^$', views.car_index, name="car_index"),
    url(r'^(?P<id>[\w-]+)/$', views.car_detail, name="car_detail"),
]

sawasawa_market/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls import url, include
from django.conf import settings
from blog import views
from django.conf.urls.static import static
from users import views as user_views
from search import urls as urls_search
from checkout import views as checkout_views




urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^search/', include(urls_search)),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('', include('checkout.urls')),
    path('', include('blog.urls')),
    path('blogo/', include('blogo.urls')),
    url(r'^jobbs/', include('jobbs.urls')),
    url(r'^houses/', include('houses.urls')),
    url(r'^cars/', include('cars.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    
    

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)

cars/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.


class Car(models.Model):
    title = models.CharField(max_length=250)
    description = models.TextField()
    fuel = models.CharField(max_length=20)
    modeli = models.CharField(max_length=20)
    owner = models.CharField(max_length=20)
    year_model = models.CharField(max_length=20)
    drive = models.CharField(max_length=20)
    price = models.IntegerField()
    image = models.ImageField(
        default='default.jpg', upload_to='image_jobbs', blank=True, null=True)
    phone = models.CharField(blank=True, max_length=15)
    email = models.CharField(max_length=20)
    address = models.CharField(help_text='Address', max_length=60)
    city = models.CharField(help_text='City', max_length=40)
    country = models.CharField(help_text='Country', max_length=30)
    date_posted = models.DateTimeField(default=timezone.now)
    

cars/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse 
from .models import Car


# Create your views here.
def car_index(request):
    cars = Car.objects.all()
    context = {'cars': cars}

    template_name = 'car_index.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'cars'
    return render(request, 'car_index.html', context)


def car_detail(request, id):
    car = get_object_or_404(Car, id=id)
    context = {'car': car}
    template_name = 'car_detail.html'
    return HttpResponse(render(request, 'car_detail.html', context))

cars/templates/car_detail.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
{% include 'blog/navigation.html' %}

<a href="{% url 'cars:car_index' %}" class="btn black-text margin-bottom-cat margin-right-cat" ><i class="fas fa-arrow-left"></i> <i class="fas fa-car fa green-text"></i>🚗 Auto </a>

<div class="container my-5">
<div class="row">

  <!-- Section: Block Content -->
  <section class="dark-grey-text">

    <h3 class="text-center font-weight-bold mb-4 pb-2">Car Detail</h3>
    <p class="text-center text-muted w-responsive mx-auto mb-5">{{car.description}} </p>
<p class="text-muted mb-3">{{ car.date_posted}}</p>

<!--{{ share_string }}-->
SHARE:
<a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
<i class="fab fa-facebook-square"></i>
</a>
<a href="https://twitter.com/home?status={{share_string}}%20{{ request.build_absolute_uri }}">
<i class="fab fa-twitter-square"></i>
</a>
<a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'> <i class="fab fa-google-plus-square"></i></a>
<a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ post.title}}&summary={{ share_string}}&source={{ request.build_absolute_uri }}">
<i class="fab fa-linkedin"></i>
</a>
    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-lg-5 mb-lg-0 mb-5">

        <img class="img-fluid img-thumbnail" src="{{ car.image.url }}" alt="" >
        <h3 class="text-center mt-3">Contact us</h3>
        <ul>
        <li class="d-flex mt-4 ">
            <span class="fa-li"><i class="fas fa-mobile-alt orange-text accent-1"></i></span>
            <div>
              <h5 class="font-weight-bold mb-1">Phone</h5>
              <p class="text-muted mb-0">{{ car.phone}}</p>
            </div>
          </li>
          <li class="d-flex mt-4 ">
            <span class="fa-li"><i class="far fa-envelope orange-text accent-1"></i></span>
            <div>
              <h5 class="font-weight-bold mb-1">Email</h5>
              <p class="text-muted mb-0">{{ car.email}}</p>
            </div>
          </li>
          <li class="d-flex mt-4 ">
            <span class="fa-li"><i class="fas fa-map-marker-alt orange-text accent-1"></i></span>
            <div>
              <h5 class="font-weight-bold mb-1">Address</h5>
              <p class="text-muted mb-0">{{ car.address}}</p>
            </div>
          </li>
          <li class="d-flex mt-4  ">
            <span class="fa-li"><i class="fas fa-map-pin orange-text accent-1"></i></span>
            <div>
              <h5 class="font-weight-bold mb-1">City</h5>
              <p class="text-muted mb-0">{{ car.city}}</p>
            </div>
          </li>
          <li class="d-flex mt-4 ">
            <span class="fa-li"><i class="fas fa-globe-africa orange-text accent-1"></i></span>
            <div>
              <h5 class="font-weight-bold mb-1 ">Country</h5>
              <p class="text-muted mb-0">{{ car.country}}</p>
            </div>
          </li>
        </ul>
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-lg-7">

        <ul class="list-unstyled fa-ul mb-0">
          <li class="d-flex mt-4 pl-4">
            <span class="fa-li"><i class="fas fa-book  cyan-text orange-text accent-1"></i></span>
            <div>
              <h5 class="font-weight-bold mb-1">Mark</h5>
              <p class="text-muted">{{ car.modeli}}</p>
            </div>
          </li>
          <li class="d-flex mt-4 pl-4">
            <span class="fa-li"><i class="fas fa-code red-text orange-text accent-1"></i></span>
            <div>
              <h5 class="font-weight-bold mb-1">Fuel</h5>
              <p class="text-muted">{{ car.fuel}}</p>
            </div>
          </li>
          <li class="d-flex mt-4 pl-4">
            <span class="fa-li"><i class="far fa-money-bill-alt  deep-purple-text"></i></span>
            <div>
              <h5 class="font-weight-bold mb-1">Price</h5>
              <p class="text-muted mb-0">{{ car.price}}</p>
            </div>
          </li>
          <li class="d-flex mt-4 pl-4">
            <span class="fa-li"><i class="far fa-calendar-alt orange-text accent-1"></i></span>
            <div>
              <h5 class="font-weight-bold mb-1">Year Model</h5>
              <p class="text-muted mb-0">{{ car.year_model}}</p>
            </div>
            <li class="d-flex mt-4 pl-4">
            <span class="fa-li"><i class="fas fa-dumbbell orange-text accent-1"></i></span>
            <div>
              <h5 class="font-weight-bold mb-1">Driver</h5>
              <p class="text-muted mb-0">{{ car.drive}}</p>
            </div>
          
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

    <hr class="my-5">

  </section>
  <!-- Section: Block Content -->


</div>
</div>

{% include 'blog/footer.html' %}
{% endblock %}

cars/templates/car_index.html
{% extends "blog/base.html" %}
{% load static %}

{% block content %}
{% include 'blog/navigation.html' %}

<h2 class="font-weight-bold mb-4 pb-2 text-center"><i class="fas fa-car-battery mr-3 orange-text"></i><i class="fas fa-truck-monster mr-3 green-text"></i><i class="fas fa-truck mr-3 blue-text"></i><i class="fas fa-tractor mr-3 red-text"></i><i class="fas fa-motorcycle mr-3 purple-text"></i> <i class="fa fa-car text-warning" aria-hidden="true"></i></h2>

<div class="container mt-5">


  <!--Section: Content-->
  <section class="dark-grey-text text-center">
{% for car in cars %}
    <!-- Section heading -->
    
    <!-- Section description -->
    <p class="text-center mx-auto w-responsive mb-5 "></p>

  	<!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-lg-4 col-md-12 mb-4">

        <!-- Featured image -->
        <div class="view overlay rounded z-depth-2 mb-4">
          <img class="card-img-top img-thumbnail img-fluid " src="{{ car.image.url }}">
          <a>
            <div class="mask rgba-white-slight"></div>
          </a>
        </div>

        <!-- Category -->
        <a href="#!" class="pink-text">
          <h6 class="font-weight-bold mb-3"><i class="fas fa-map pr-2"></i>New</h6>
        </a>
        <!-- Post title -->
        <h4 class="font-weight-bold mb-3"><strong>{{ car.title }}</strong></h4>
        <!-- Post data -->
        <p>by <a class="font-weight-bold">{{ car.owner }}</a>, {{ car.date_posted }}</p>
        <!-- Excerpt -->
        <p class="dark-grey-text">{{car.description|linebreaks|truncatewords:10}}</p>
        <!-- Read more button -->
        <a class="btn btn-pink btn-rounded btn-md"  href="{% url 'cars:car_detail' id=car.id %}">Read more</a>
        

      </div>
      <!-- Grid column -->

     
  

    </div>
    <hr>
    <!-- Grid row -->
{% endfor %}
  </section>
  <!--Section: Content-->


</div>

{% include 'blog/footer.html' %}
{% endblock %}