blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static






from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
)

from . import views

urlpatterns = [
    path('', views.PostListView, name='blog-home'),
    path('user/<str:username>', views.UserPostListView, name='user-posts'),
    path('post/<int:id>/', views.PostDetailView, name='post-detail'),
    path('post/new/', views.PostCreateView, name='post-create'),
    path('post/<int:id>/update/', views.PostUpdateView, name='post-update'),
    path('post/<int:id>/delete/', views.PostDeleteView, name='post-delete'),
    path('about/', views.about, name='blog-about'),
    #path('pay_success/', views.pay_success, name='blog-pay_success'),
    path('footer/', views.footer, name='blog-footer'),
    path('navigation/', views.navigation, name='blog-navigation'),
    path('success/', views.Success, name='blog-success'),
    path('contact/', views.Contact, name='blog-contact'),
    path('base/', views.base, name='blog-base'),
]

cars/urls.py
from django.conf.urls import url
from .views import (car_index)
from . import views

app_name='cars'

urlpatterns = [
    url(r'^$', views.car_index, name="car_index"),
    url(r'^(?P<id>[\w-]+)/$', views.car_detail, name="car_detail"),
]

houses/urls.py
from django.conf.urls import url
from .views import (house_index)
from . import views

app_name='houses'

urlpatterns = [
    url(r'^$', views.house_index, name="house_index"),
    url(r'^(?P<id>[\w-]+)/$', views.house_detail, name="house_detail"),
]

jobbs/urls.py
from django.conf.urls import url
from .views import (job_index)
from . import views

app_name='jobbs'

urlpatterns = [
    url(r'^$', views.job_index, name="job_index"),
    url(r'^(?P<id>[\w-]+)/$', views.job_detail, name="job_detail"),
]

sawasawa_market/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf.urls import url, include
from django.conf import settings
from blog import views
from django.conf.urls.static import static
from users import views as user_views
from search import urls as urls_search
from checkout import views as checkout_views




urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^search/', include(urls_search)),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('', include('checkout.urls')),
    path('', include('blog.urls')),
    path('blogo/', include('blogo.urls')),
    url(r'^jobbs/', include('jobbs.urls')),
    url(r'^houses/', include('houses.urls')),
    url(r'^cars/', include('cars.urls')),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    
    

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)

blog/models.py
from __future__ import unicode_literals
from django.db import models
import datetime
from django.utils import timezone
from django.db.models.signals import pre_save
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image
from django.dispatch import receiver
from django.db.models.signals import pre_delete


class Post(models.Model):
    phone = models.CharField(blank=True, max_length=15)
    address = models.CharField(help_text='Address', max_length=60)
    city = models.CharField(help_text='City', max_length=40)
    country = models.CharField(help_text='Country', max_length=30)
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=300)
    price = models.IntegerField()
    date_posted = models.DateTimeField(default=timezone.now)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(
        default='default.jpg', upload_to='image_main_post')


    class Meta:
        ordering = ['-id']
        

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'id': self.id})


    def __str__(self):
            return str(self.title)


class Images(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, default=None)
    image = models.ImageField(
        default='default.jpg', upload_to='image_post', blank=True, null=True)
    

    def __str__(self):
            return str(self.post.id)

blog/forms.py
from django import forms
from .models import Post
from django.contrib.auth.models import User


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title', 'description',
            'price', 'image', 'phone', 'address', 'city', 'country')


class PostEditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title', 'description',
            'price', 'image', 'phone', 'address', 'city', 'country')


class ContactForm(forms.Form):
    contact_name = forms.CharField(required=True)
    contact_email = forms.EmailField(required=True)
    content = forms.CharField(widget=forms.Textarea, required=True)

blog/views.py
from django.conf import settings
from django.core.mail import send_mail, BadHeaderError
from django.shortcuts import render, get_object_or_404, redirect
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.template.loader import get_template
from .forms import ContactForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.forms import modelformset_factory
from django.contrib import messages
import urllib.parse
from .forms import *
from django.urls import reverse
from .models import Post, Images
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404


def home(request):
    context = {
        'posts': Post.objects.all(),
        'images': Images.objects.all()
    }
    return render(request, 'blog/home.html', context)


def PostListView(request):
    context = {
        'posts': Post.objects.all(),
        'images': Images.objects.all()
    }
    model = Post
    template_name = 'blog/home.html'  
    context_object_name = 'posts'
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 8)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if page is None:
        start_index = 0
        end_index = 7
    else:
        (start_index, end_index) = proper_pagination(posts, index=4)

    page_range = list(paginator.page_range)[start_index:end_index]

    context = {
        'posts': posts,
        'page_range': page_range,
    }    
    return render(request, 'blog/home.html', context)


def proper_pagination(posts, index):
    start_index = 0
    end_index = 7
    if posts.number > index:
        start_index = posts.number - index
        end_index = start_index + end_index
    return (start_index, end_index)


def UserPostListView(request, username):
    context = {
        'posts': Post.objects.filter(author__username=username),
    }
    model = Post
    template_name = 'blog/user_posts.html'  
    context_object_name = 'posts'

    def get_queryset(self):
        username = get_object_or_404(
            User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')
    return render(request, 'blog/user_posts.html', context)


def PostDetailView(request, id):
    post = Post.objects.get(id=id)
    context = {
        'post': post,
    }
    model = Post 
    template_name = 'blog/user_posts.html'  
    context_object_name = 'posts'
    return render(request, 'blog/post_detail.html', context)


@login_required
def PostCreateView(request):
    ImageFormset = modelformset_factory(Images, fields=('image',), extra=4)
    if request.method == 'POST':
        form = PostCreateForm(request.POST, request.FILES)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            print(formset.cleaned_data)
            for f in formset:
                print(f.cleaned_data)
                try:
                    photo = Images(post=post, image=f.cleaned_data.get(
                        'image'))
                    photo.save()
                except Exception as e:
                    break
            messages.success(request, "Post has been successfully created.")
            return render(request, 'blog/home.html')
    else:
        form = PostCreateForm()
        formset = ImageFormset(queryset=Images.objects.none())
    context = {
        'form': form,
        'formset': formset,
    }
    return render(request, 'blog/post_form.html', context)   


def PostUpdateView(request, id):
    post = get_object_or_404(Post, id=id)
    ImageFormset = modelformset_factory(
        Images, fields=('image',), extra=4, max_num=4)
    if post.author != request.user:
        raise Http404()
    if request.method == "POST":
        form = PostEditForm(request.POST or None, instance=post)
        formset = ImageFormset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            form.save()
            print(formset.cleaned_data)
            data = Images.objects.filter(post=post)
            for index, f in enumerate(formset):
                if f.cleaned_data:
                    if f.cleaned_data['id'] is None:
                        photo = Images(
                            post=post, image=f.cleaned_data.get('image'))
                        photo.save()
                    elif f.cleaned_data['image'] is False:
                        photo = Images.objects.get(
                            id=request.POST.get('form-' + str(index) + '-id'))
                        photo.delete()
                    else:
                        photo = Images(
                            post=post, image=f.cleaned_data.get('image'))
                        d = Images.objects.get(id=data[index].id)
                        d.image = photo.image
                        d.save()
            messages.success(
                request, "{} has been successfully updated!".format(
                    post.title))
            return HttpResponseRedirect(post.get_absolute_url())
    else:
        form = PostEditForm(instance=post)
        formset = ImageFormset(queryset=Images.objects.filter(post=post))
    context = {
     'form': form,
     'post': post,
     'formset': formset,
    }
    return render(request, 'blog/post_form.html', context)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def PostDeleteView(request, id):   
    obj = get_object_or_404(Post, id=id)
    obj.delete()        
    query = Post.objects.filter(id=id)
    query.delete()
    messages.warning(request, 'post has been successfully deleted!')
    return redirect('blog-home')

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})


def Contact(request):
    Contact_Form = ContactForm
    if request.method == 'POST':
        form = Contact_Form(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get('contact_name')
            contact_email = request.POST.get('contact_email')
            contact_content = request.POST.get('content')

            template = get_template('blog/contact_form.txt')
            context = {
                'contact_name': contact_name,
                'contact_email': contact_email,
                'contact_content': contact_content,
            }           
            content = template.render(context)

            email = EmailMessage(
             "New contact form email",
             content,
             "Creative web" + '',
             ['masasimpafra@gmail.com'],
             headers={'Reply To': contact_email}
            )

        email.send()

        return redirect('blog-success')
    return render(request, 'blog/contact.html', {'form': Contact_Form})


def Success(request):
    return render(request, 'blog/success.html')


def footer(request):
    return render(request, 'blog/footer.html', {'title': 'footer'})


def navigation(request):
    return render(request, 'blog/navigation.html', {'title': 'navigation'})


def base(request):
    return render(request, 'blog/base.html', {'title': 'base'})

blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% block content  %}
<!--navigation-->
{% include 'blog/navigation.html' %}
  <hr class="mb-5 mt-4">
<!-- categories button-->

<div class="calling">
<div class="text-center d-none d-sm-none d-md-none d-lg-block">  
<!--Unique-->
<a href="{% url 'cars:car_index' %}" class="btn black-text margin-bottom-cat margin-right-cat" > <i class="fas fa-car fa-3x green-text"></i>🚗 Auto </a>

<!--Pink-->
<a  href="{% url 'houses:house_index' %}" class="btn margin-bottom-cat margin-right-cat" ><i class="fas fa-city fa-3x pink-text"></i>🏪 Commercial </a>
<!--Indigo-->
<a  href="{% url 'houses:house_index' %}" class="btn margin-bottom-cat margin-right-cat" ><i class="fas fa-store-alt fa-3x indigo-text"></i>🏠 house for sell/rent </a>

<!--Purple-->
<a href="{% url 'jobbs:job_index' %}" class="btn margin-bottom-cat margin-right-cat" aria-hidden="true"><i class="fas fa-user-graduate fa-3x purple-text"></i><i class="fas fa-user-md fa-3x deep-purple-text"></i><strong> training & jobs</a>   
</div>
</div>
 <!-- image main post -->

<div class="flex-container col s12 m6">
    {% for post in posts %}
    <div class="display_posts">
<div id="wrap" class="columns_4">
	<div id="columns" class="columns_4">
  <figure>
<a href="{% url 'post-detail' post.id %}"><img  src="{{ post.image.url }}" alt="image.image-{{post.title}}" class='card-img-top text-shadow'/></a>
  <div class="spacing-on-detail text-center">
	<span><a  href="{% url 'post-detail' post.id %}"><figcaption class="green-text  capitalise text-center text-uppercase">{{ post.title }}</figcaption></a></span><br>
  <span><a href="{% url 'user-posts' post.author.username %}"><figcaption class="orange-text  text-capitalize">Seller: {{ post.author }}</figcaption></a></span><br>
  <span class="price "><strong>Price:$ {{ post.price }}-</strong></span><br>
  <h5 class="blue-text "><small>{{ post.date_posted|date:"F d, Y" }}</small></h5>
  </div>
    <a class="button" href="{% url 'post-detail' post.id %}">Read More</a>
	</figure>
</div>
</div>
</div>
{% endfor %}
</div>
 <div class="container my-5 py-5 z-depth-1">
<!--Section: Content calling-->
    <section class="px-md-5 mx-md-5 text-center dark-grey-text">
<!--Grid row-->
      <div class="row d-flex justify-content-center">

        <!--Grid column-->
        <div class="col-xl-6 col-md-8">

          <h3 class="font-weight-bold orange-text">Sell your house, Car...</h3>

          <p class="text-muted">At SAWASAWA-Market we are known online market with millions of buyers everyday, selling with us you never regret</p>

          <a class="btn btn-info btn-md ml-0 mb-5" href="{% url 'post-create' %}" role="button">Sell Now</a>

          <p class="mb-4 font-weight-bold">Trusted by 1 000 000 + cusomers &amp; Real estates</p>

          <!--Grid row-->
          <div class="row">

            <!--First column-->
            <div class="col-lg-3 col-md-6 d-flex align-items-center justify-content-center">
              <img src="https://mdbootstrap.com/img/logo/brands/nike.png" class="img-fluid" alt="Nike - logo"
                style="max-height: 40px">
            </div>
            <!--/First column-->

            <!--Second column-->
            <div class="col-lg-3 col-md-6 d-flex align-items-center justify-content-center">
              <img src="https://mdbootstrap.com/img/logo/brands/amazon.png" class="img-fluid" alt="Amazon - logo"
                style="max-height: 40px">
            </div>
            <!--/Second column-->

            <!--Third column-->
            <div class="col-lg-3 col-md-6 d-flex align-items-center justify-content-center">
              <img src="https://mdbootstrap.com/img/logo/brands/sony.png" class="img-fluid" alt="Sony - logo"
                style="max-height: 40px">
            </div>
            <!--/Third column-->

            <!--Fourth column-->
            <div class="col-lg-3 col-md-6 d-flex align-items-center justify-content-center">
              <img src="https://mdbootstrap.com/img/logo/brands/samsung.png" class="img-fluid" alt="Samsung - logo"
                style="max-height: 40px">
            </div>
            <!--/Fourth column-->

          </div>
          <!--/Grid row-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->
</section>
    <!--Section: Content-->
    </div>

<!--pagination-->


<ul class="pagination text-center">
  {% if posts.has_previous %}
    <li class="page-item">
    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
      <a href="?page={{ posts.previous_page_number }}" class="btn btn-outline-info mb-4">Prev</a>
    </li>
  {% endif %}

  {% for p in page_range %}
    {% if posts.number == p %}
      <li class="page-item active ">
        <a href="?page={{ p }}" class="btn btn-info mb-4">{{ p }}</a>
      </li>
    {% else %}
      <li class="page-item">
        <a href="?page={{ p }}" class="btn btn-outline-info mb-4">{{ p }}</a>
      </li>
    {% endif %}
  {% endfor %}

  {% if posts.has_next %}
    <li class="page-item">
      <a href="?page={{ posts.next_page_number }}" class="btn btn-outline-info mb-4">Next</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ posts.paginator.num_pages }}">Last</a>
    </li>
  {% endif %}
</ul>
<!-- footer-->
{% include 'blog/footer.html' %}
{% endblock content %}
    

blog/templates/blog/navigation.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content  %}


<!--Navbar-->
  <navbar class="navbar navbar-expand-lg navbar-dark rgba-red-strong">
<a href="{% url 'blog-home'%}"><img class="navbar-brand mr-1" src="{% static 'img/logosawa.png'%}" alt="logo-image" style="width:150px;height:80px;"></img></a> 
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog-home'%}"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item ">
            <a class="nav-link font-weight-bold success-lighter-hover text-shadow" href="{% url 'blog-home' %}">Home </a>
          </li>
          <li class="nav-item">
            <a class="nav-link font-weight-bold success-lighter-hover text-shadow" href="{% url 'blog-about' %}">About us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link font-weight-bold success-lighter-hover text-shadow" href="{% url 'blogo_index' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link font-weight-bold success-lighter-hover text-shadow" href="{% url 'jobbs:job_index' %}">Jobs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link font-weight-bold success-lighter-hover text-shadow" href="{% url 'blog-contact' %}">Contact</a>
          </li>
          <li class="nav-item btn-group">
            <a class="nav-link dropdown-toggle font-weight-bold success-lighter-hover text-shadow" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">Properties
            </a>
            <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">All</a>
              <a class="dropdown-item" href="{% url 'houses:house_index' %}"><i class="fas fa-home green-text"></i> Villa</a>
              <a class="dropdown-item" href="{% url 'houses:house_index' %}"><i class="far fa-building red-text"></i> Apartment</a>
              <a class="dropdown-item" href="{% url 'houses:house_index' %}"><i class="fas fa-city yellow-text"></i> Commercial</a>
            </div>
          </li>
           <li class="nav-item btn-group ">
            <a class="nav-link dropdown-toggle font-weight-bold success-lighter-hover text-shadow" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">Automobile
            </a>
            <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">All</a>
              <a class="dropdown-item" href="{% url 'cars:car_index' %}"><i class="fas fa-car-side yellow-text"></i> Vehicles</a>
              <a class="dropdown-item" href="{% url 'cars:car_index' %}"><i class="fas fa-motorcycle green-text"></i> Motobike</a>
              <a class="dropdown-item" href="{% url 'cars:car_index' %}"><i class="fas fa-car-battery red-text"></i> Spare parts</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0 ml-auto" action="{% url 'search' %}" method="GET" value="{{request.GET.q}}">
        <div >
    <input class="form-control mr-sm-2" type="text" name='q' placeholder="Search" aria-label="Search">
    </div>
    
  </form>
  
  <div class="navbar-nav float-right">
  {% if user.is_authenticated %}
  <a class="nav-item nav-link font-weight-bold success-lighter-hover text-shadow" href="{% url 'profile' %}">Profile</a>
  <a class="nav-item nav-link  font-weight-bold success-lighter-hover text-shadow" href="{% url 'post-create' %}">Sell</a>
  <a class="nav-item nav-link  font-weight-bold success-lighter-hover text-shadow" href="{% url 'checkout' %}">Donate</a>
  <a class="nav-item nav-link font-weight-bold success-lighter-hover text-shadow" href="{% url 'logout' %}">Log Out</a>


  {% else %}
        <a class="nav-item nav-link font-weight-bold success-lighter-hover  text-shadow" href="{% url 'login' %}">Log In</a>
        <a class="nav-item nav-link font-weight-bold success-lighter-hover text-shadow" href="{% url 'register' %}">Register</a>
        <a class="nav-item nav-link  font-weight-bold success-lighter-hover text-shadow" href="{% url 'checkout' %}">Donate</a>
          <a class="nav-item nav-link font-weight-bold success-lighter-hover  text-shadow" href="{% url 'login' %}">Sell</a>
  {% endif %}
  </div>
      </div>
    </div>
  </navbar>
  <!-- Navbar-->
 {% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content  %}
{% include 'blog/navigation.html' %}
<!-- categories button-->
<div class="container">
<div class="row">

<div class="calling">
<div class="text-center d-none d-sm-none d-md-none d-lg-block">  
<!--Unique-->
<a href="{% url 'cars:car_index' %}" class="btn black-text margin-bottom-cat margin-right-cat" > <i class="fas fa-car fa-3x green-text"></i>🚗 Auto </a>

<!--Pink-->
<a  href="{% url 'houses:house_index' %}" class="btn margin-bottom-cat margin-right-cat" ><i class="fas fa-city fa-3x pink-text"></i>🏪 Commercial </a>
<!--Indigo-->
<a  href="{% url 'houses:house_index' %}" class="btn margin-bottom-cat margin-right-cat" ><i class="fas fa-store-alt fa-3x indigo-text"></i>🏠 house for sell/rent </a>

<!--Purple-->
<a href="{% url 'jobbs:job_index' %}" class="btn margin-bottom-cat margin-right-cat" aria-hidden="true"><i class="fas fa-user-graduate fa-3x purple-text"></i><i class="fas fa-user-md fa-3x deep-purple-text"></i><strong> training & jobs</a>
    
</div>
</div>
<!-- image on post details-->
<div class="display_posts text-center mt-4 col-sm-12">
<div id="" class="columns_4 text-center ">
	<div id="columns" class="columns_4 ">
  <figure class="col-sm-12 ">
{% for p in post.images_set.all %}
    {% if p.image %}
      
      <a href="#" class="gallery" >
        <img src="{{ p.image.url }}" alt="" class="img-thumbnail card-img-top text-shadow mt-4 ml-4"  onclick="myFunction(this);" >
      </a>
	
    {% endif %}
    {% endfor %}
    </figure>
</div>
</div>
</div>
<!-- The expanding image container -->
<div class="container">
  <!-- Close the image -->
  <span onclick="this.parentElement.style.display='none'" class="closebtn">&times;</span>

  <!-- Expanded image -->
  <img id="expandedImg" style="width:80%" class="img-thumbnail">

  <!-- Image text -->
  <div id="imgtext"></div>
</div>
        
<!-- post details seller, price and description -->

<div class="container z-depth-1 my-5 py-5">

  <!-- Section -->
  <section>
    
    <style>
      .border-top {
        border-top-width: 2px !important;
      }
  	</style>

    <h6 class="font-weight-bold text-center grey-text text-uppercase small mb-4">{{ post.date_posted }}</h6>
    <h3 class="font-weight-bold text-center dark-grey-text pb-2">{{ post.title}}</h3>
    <hr class="w-header my-4">
    <p class="lead text-center text-muted pt-2 mb-5 text-capitalize">{{ post.description }}</p>

    <div class="row d-flex justify-content-center">

      <div class="col-md-6 col-lg-5 col-xl-4">
        <h5 class="font-weight-normal border-top border-secondary pt-4 mb-4"><a class="dark-grey-text" href="#">
            PRICE</a></h5>
        <p class="font-weight-bold text-muted mb-5 pb-md-3">$ {{ post.price }}.00</p>
      </div>

      <div class="col-md-6 col-lg-5 col-xl-4">
        <h5 class="font-weight-normal border-top border-secondary pt-4 mb-4"><a class="dark-grey-text"
            href="#">SELLER</a></h5>
        <p class="font-weight-bold text-muted mb-5 pb-md-3">{{ post.author}}</p>
      </div>

      <div class="w-100"></div>
    </div>
  </section>
  <!-- Section -->

</div>
      
  <!-- if user is authenticated this will show up on the post detail -->

 {% if post.author == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' post.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' post.id %}">Delete</a>
          </div>
  {% endif %}
</div>
</div>
<!-- address for the owner of the post-->
  <div class="container py-5  z-depth-1">
  <section class="p-md-3 mx-md-5 text-lg-left">
    <div class="row">
      <div class="col-12">
        <h3 class="dark-grey-text text-center font-weight-bold">ADDRESS & CONTACT
          
        </h3>
      </div>
    </div>
    <div class="row mt-5">
      <div class="col-lg-3 col-md-6 mb-lg-0 mb-5">
        <div class=" mt-3 text-center">
          <i class="fa fa-map-marker-alt fa-2x indigo-text mb-4"></i>
          <h6 class="font-weight-lighter deep-orange-text">Post address:</h6>
          <h4 class="font-weight-bold text-capitalize">{{ post.address }}</h4>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 mb-lg-0 mb-5">
        <div class=" mt-3 text-center">
          <i class="far fa-map fa-2x pink-text mb-4"></i>
          <h6 class="font-weight-lighter deep-orange-text">City:</h6>
          <h4 class="font-weight-bold text-capitalize">{{ post.city }}</h4>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 mb-md-0 mb-5">
        <div class=" mt-3 text-center">
          <i class="fa fa-globe-africa fa-2x amber-text mb-4"></i>
          <h6 class="font-weight-lighter deep-orange-text">Country:</h6>
         	<h4 class="font-weight-bold text-capitalize">{{ post.country }}</h4>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 mb-md-0 mb-5">
        <div class=" mt-3 text-center">
          <i class="fas fa-phone-volume fa-2x green-text mb-4"></i>
          <h6 class="font-weight-lighter deep-orange-text">Phone:</h6>
         	<h4 class="font-weight-bold text-capitalize">Tel: {{ post.phone }}</h4>
        </div>
      </div>
    </div>
  </section>
</div>

{% include 'blog/footer.html' %}
{% endblock content %}
    